pipeline {
    agent any
    tools{
        maven 'maven'
    }
    stages{
        stage('Build maven'){
            steps{
                checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Midgardsormrr/karts-backend']])
                bat 'mvn clean package'
            }
        }

        stage('Unit Tests') {
            steps {
                // Run Maven 'test' phase. It compiles the test sources and runs the unit tests
                bat 'mvn test' // Use 'bat' for Windows agents or 'sh' for Unix/Linux agents
            }
        }

        stage('Build docker image'){
            steps{
                script{
                    bat 'docker build -t dguerra15/book_service:latest .'
                }
            }
        }
        stage('Push image to Docker Hub'){
            steps{
                dir("karts-backend"){
                    script{
                       withDockerRegistry([string(credentialsId: 'docker-credentials')]) {
                            bat 'docker build -t dguerra15/karts-backend:latest .'
                            bat 'docker push dguerra15/karts-backend:latest'
                       }
                    }
                }
            }
        }
    }
}