pipeline {
    agent any
    tools{
        maven 'maven'
    }
    stages{
        stage('Build maven'){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Midgardsormrr/Tingeso']])
                dir("karts-backend"){
                    bat 'mvn clean package'
                }
            }
        }

        stage('Unit Tests') {
            steps {
                dir("karts-backend"){
                    bat 'mvn test'
                }
            }
        }

        stage('Build docker image'){
            steps{
                script{
                    bat 'docker build -t dguerra15/karts-backend:latest .'
                }
            }
        }
        stage('Push image to Docker Hub'){
            steps{
                dir("karts-backend"){
                    script{
                       withDockerRegistry([string(credentialsId: 'docker-credentials')]) {
                            bat 'docker build -t dguerra15/karts-backend:latest ..'
                            bat 'docker push dguerra15/karts-backend:latest'
                       }
                    }
                }
            }
        }
    }
}