
services:
  # Database service
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: Karts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  # Frontend services
  frontend1:
    image: dguerra15/karts-frontend:latest
    networks:
      - frontend-network

  frontend2:
    image: dguerra15/karts-frontend:latest
    networks:
      - frontend-network

  frontend3:
    image: dguerra15/karts-frontend:latest
    networks:
      - frontend-network

  # Backend services
  backend1:
    image: dguerra15/karts-backend:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Karts
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SERVER_PORT: 8090
    networks:
      - backend-network
    depends_on:
      - db

  backend2:
    image: dguerra15/karts-backend:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Karts
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SERVER_PORT: 8090
    networks:
      - backend-network
    depends_on:
      - db

  backend3:
    image: dguerra15/karts-backend:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Karts
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SERVER_PORT: 8090
    networks:
      - backend-network
    depends_on:
      - db

  # Nginx for frontend load balancing
  nginx-frontend:
    image: nginx:latest
    ports:
      - "8070:80"
    volumes:
      - ./nginx-frontend.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - frontend-network

  # Nginx for backend load balancing
  nginx-backend:
    image: nginx:latest
    ports:
      - "8090:8090"
    volumes:
      - ./nginx-backend.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - backend-network

networks:
  frontend-network:
  backend-network:

volumes:
  postgres_data: