
services:
  # Nginx for backend load balancing
  nginx-backend:
    image: nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx-backend.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - backend-network
    
  # Nginx for frontend load balancing
  nginx-frontend:
    image: nginx
    ports:
      - "8070:8070"
    restart: always 
    volumes:
      - ./nginx-frontend.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - frontend-network


  # Database service
  postgres:
    container_name: kart-postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - kart-postgres:/var/lib/postgresql/data
    networks:
      - backend-network

# Backend services
  backend1:
    image: dguerra15/karts-backend:latest
    ports:
      - 8091:8090
    environment:
      DB_HOST: kart-postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    networks:
      - backend-network
    depends_on:
      - postgres
    

  backend2:
    image: dguerra15/karts-backend:latest
    ports:
      - 8092:8090
    environment:
      DB_HOST: kart-postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    networks:
      - backend-network
    depends_on:
      - postgres
    


  backend3:
    image: dguerra15/karts-backend:latest
    ports:
      - 8093:8090
    environment:
      DB_HOST: kart-postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    networks:
      - backend-network
    depends_on:
      - postgres

  # Frontend services
  frontend1:
    image: dguerra15/karts-frontend:latest
    networks:
      - frontend-network
    ports:
      - "3001:3000"

  frontend2:
    image: dguerra15/karts-frontend:latest
    networks:
      - frontend-network
    ports:
      - "3002:3000"

  frontend3:
    image: dguerra15/karts-frontend:latest
    networks:
      - frontend-network
    ports:
      - "3003:3000"
networks:
  frontend-network:
  backend-network:

volumes:
  kart-postgres: